server:
  servlet:
    context-path: /
  port: 8080

spring:
  application:
    name: taurus
  datasource:
    url: jdbc:mysql://localhost:3306/starschool_taurus_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:
  sql:
    init:
      mode: never
      data-locations: classpath*:/db-import.sql
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    # 若由实体Bean自动创建表，则ddl-auto设置为always，如果由脚本创建表，则设置为none
    generate-ddl: true
    show-sql: true
    open-in-view: true
#  data:
#    redis:
#      host: localhost #此为默认值
#      port: 6379 #此为默认值
#      database: 0 #此为默认值
#      password: #此为默认值
#      timeout: 30000s #连接超时时间，默认1天
#      lettuce:
#        shutdown-timeout: 100ms #关闭超时时间 默认100ms
#        pool:
#          max-active: 8 # 连接池最大连接数 默认 8（-1 ：表示没有限制）
#          max-wait: 60000ms # 连接池最大阻塞等待时间 默认-1ms （-1 :表示没有限制） 这里设置1分钟
#          max-idle: 8 # 最大空闲连接  默认 8
#          min-idle: 0 # 最小空闲连接  默认 0
